import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { Providers } from "@/app/components/Providers";
// import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import { AuthProvider } from "@/app/contexts/AuthContext";

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="es" data-scroll-behavior="smooth">
      <body >
          <Providers>
            <AuthProvider>
              {children}
              <ToastContainer position="top-right" autoClose={3000} />
            </AuthProvider>
          </Providers>
      </body>
    </html>
  );
}









// "use client"
// import "./globals.scss";
// import { useState } from "react";
// import { Provider } from "react-redux";
// import store from "@/redux/store";
// import { Initialload } from "@/app/components/layouts/contextapi";

// const RootLayout = ({ children }: any) => {

//   const [pageloading, setpageloading] = useState(false)

//   return (
//     <Provider store={store}>
//       <Initialload.Provider value={{ pageloading, setpageloading }}>
//         {children}
//       </Initialload.Provider>
//     </Provider>
//   );
// }
// export default RootLayout;





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
